language: php
sudo: false

php:
    - 5.4

env:
    - DB=MYSQL CORE_RELEASE=3.1

matrix:
  include:
    - php: 5.5
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3.2
    - php: 5.6
      env: DB=SQLITE CORE_RELEASE=3
    - php: 5.4
      env: DB=SQLITE CORE_RELEASE=3.1 COVERAGE=1

before_script:
  - composer self-update
  - phpenv rehash
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - "if [ \"$COVERAGE\" -ne \"1\" ]; then phpunit -c omnipay-ui/phpunit.xml.dist; fi"
  - "if [ \"$COVERAGE\" -eq \"1\" ]; then phpunit -c omnipay-ui/phpunit.xml.dist --coverage-clover ~/builds/ss/omnipay-ui/coverage.clover; fi"

after_script: ./omnipay-ui/tests/travis/upload_coverage.sh
